### ISSUE TITLE
webpack error in console on navbar: blog click

### ISSUE THREAD

**Issue by Mic1** [josefaidt/svelte-routify-mdsvex-demo#1]
Uncaught (in promise) TypeError: can't access property Symbol.iterator, _blog_data_json__WEBPACK_IMPORTED_MODULE_4__.find(...) is undefined

    posts blog.svx:11
    instance blog.svx:10
    init index.mjs:1436
    
blog.svx: 11: let posts = routes.filter(route => /^\/blog\/[A-z0-9\/\-]*$/gi.test(route.shortPath)).map(route => {
    const [,frontmatter] = data.find(([path]) => route.absolutePath === path)
    return Object.assign(route, { frontmatter })
  })

Running unaltered code from zip download. Thanks in advance

**Comment by Mic1** [comment]
Fixed by editing blog.svx to
```
let posts = routes.filter(route => /^\/_blog\/[A-z0-9\/\-]*$/gi.test(route.shortPath)).map(route => {
    const [,frontmatter] = data.find(([path]) => route.absolutePath === path)
    return Object.assign(route, { frontmatter })
  })
```
changed blog to _blog

**Comment by josefaidt** [comment]
hey @Mic1 👋 sorry just saw this issue. I'll be updating this repo with a modified template version as I've migrated to using [svite](https://github.com/dominikg/svite)

**Comment by Mic1** [comment]
cool thanks :-)

    On Monday, October 5, 2020, 9:39:21 AM MDT, josef <notifications@github.com> wrote:  
 
 


hey @Mic1 👋 sorry just saw this issue. I'll be updating this repo with a modified template version as I've migrated to using svite
